// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockRequester.DataAccess.Data;

#nullable disable

namespace StockRequester.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockRequester.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulky Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water Rocks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nice Books"
                        });
                });

            modelBuilder.Entity("StockRequester.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Name = "Edinburgh"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Name = "Glasgow"
                        });
                });

            modelBuilder.Entity("StockRequester.Models.TransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiscNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("OriginLocationId");

                    b.ToTable("TransferRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DestinationLocationId = 2,
                            Item = "Harry Potter",
                            OriginLocationId = 1,
                            Quantity = 10,
                            Reason = "Need more"
                        });
                });

            modelBuilder.Entity("StockRequester.Models.Location", b =>
                {
                    b.HasOne("StockRequester.Models.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockRequester.Models.TransferRequest", b =>
                {
                    b.HasOne("StockRequester.Models.Company", "Company")
                        .WithMany("TransferRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockRequester.Models.Location", "DestinationLocation")
                        .WithMany("TransferRequestsToThisDestination")
                        .HasForeignKey("DestinationLocationId");

                    b.HasOne("StockRequester.Models.Location", "OriginLocation")
                        .WithMany("TransferRequestsFromThisOrigin")
                        .HasForeignKey("OriginLocationId");

                    b.Navigation("Company");

                    b.Navigation("DestinationLocation");

                    b.Navigation("OriginLocation");
                });

            modelBuilder.Entity("StockRequester.Models.Company", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("StockRequester.Models.Location", b =>
                {
                    b.Navigation("TransferRequestsFromThisOrigin");

                    b.Navigation("TransferRequestsToThisDestination");
                });
#pragma warning restore 612, 618
        }
    }
}
